// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module aximm_test0_fill_data_times_v2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        strmDstPxl_dout,
        strmDstPxl_empty_n,
        strmDstPxl_read,
        strmDstPxl_num_data_valid,
        strmDstPxl_fifo_cap,
        nSize_dout,
        nSize_empty_n,
        nSize_read,
        nSize_num_data_valid,
        nSize_fifo_cap,
        nTimes_dout,
        nTimes_empty_n,
        nTimes_read,
        nTimes_num_data_valid,
        nTimes_fifo_cap,
        m_axi_mm_video_0_AWVALID,
        m_axi_mm_video_0_AWREADY,
        m_axi_mm_video_0_AWADDR,
        m_axi_mm_video_0_AWID,
        m_axi_mm_video_0_AWLEN,
        m_axi_mm_video_0_AWSIZE,
        m_axi_mm_video_0_AWBURST,
        m_axi_mm_video_0_AWLOCK,
        m_axi_mm_video_0_AWCACHE,
        m_axi_mm_video_0_AWPROT,
        m_axi_mm_video_0_AWQOS,
        m_axi_mm_video_0_AWREGION,
        m_axi_mm_video_0_AWUSER,
        m_axi_mm_video_0_WVALID,
        m_axi_mm_video_0_WREADY,
        m_axi_mm_video_0_WDATA,
        m_axi_mm_video_0_WSTRB,
        m_axi_mm_video_0_WLAST,
        m_axi_mm_video_0_WID,
        m_axi_mm_video_0_WUSER,
        m_axi_mm_video_0_ARVALID,
        m_axi_mm_video_0_ARREADY,
        m_axi_mm_video_0_ARADDR,
        m_axi_mm_video_0_ARID,
        m_axi_mm_video_0_ARLEN,
        m_axi_mm_video_0_ARSIZE,
        m_axi_mm_video_0_ARBURST,
        m_axi_mm_video_0_ARLOCK,
        m_axi_mm_video_0_ARCACHE,
        m_axi_mm_video_0_ARPROT,
        m_axi_mm_video_0_ARQOS,
        m_axi_mm_video_0_ARREGION,
        m_axi_mm_video_0_ARUSER,
        m_axi_mm_video_0_RVALID,
        m_axi_mm_video_0_RREADY,
        m_axi_mm_video_0_RDATA,
        m_axi_mm_video_0_RLAST,
        m_axi_mm_video_0_RID,
        m_axi_mm_video_0_RFIFONUM,
        m_axi_mm_video_0_RUSER,
        m_axi_mm_video_0_RRESP,
        m_axi_mm_video_0_BVALID,
        m_axi_mm_video_0_BREADY,
        m_axi_mm_video_0_BRESP,
        m_axi_mm_video_0_BID,
        m_axi_mm_video_0_BUSER,
        pDstPxl_dout,
        pDstPxl_empty_n,
        pDstPxl_read,
        pDstPxl_num_data_valid,
        pDstPxl_fifo_cap
);

parameter    ap_ST_fsm_state1 = 4'd1;
parameter    ap_ST_fsm_state2 = 4'd2;
parameter    ap_ST_fsm_state3 = 4'd4;
parameter    ap_ST_fsm_state4 = 4'd8;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [127:0] strmDstPxl_dout;
input   strmDstPxl_empty_n;
output   strmDstPxl_read;
input  [2:0] strmDstPxl_num_data_valid;
input  [2:0] strmDstPxl_fifo_cap;
input  [31:0] nSize_dout;
input   nSize_empty_n;
output   nSize_read;
input  [2:0] nSize_num_data_valid;
input  [2:0] nSize_fifo_cap;
input  [31:0] nTimes_dout;
input   nTimes_empty_n;
output   nTimes_read;
input  [2:0] nTimes_num_data_valid;
input  [2:0] nTimes_fifo_cap;
output   m_axi_mm_video_0_AWVALID;
input   m_axi_mm_video_0_AWREADY;
output  [63:0] m_axi_mm_video_0_AWADDR;
output  [0:0] m_axi_mm_video_0_AWID;
output  [31:0] m_axi_mm_video_0_AWLEN;
output  [2:0] m_axi_mm_video_0_AWSIZE;
output  [1:0] m_axi_mm_video_0_AWBURST;
output  [1:0] m_axi_mm_video_0_AWLOCK;
output  [3:0] m_axi_mm_video_0_AWCACHE;
output  [2:0] m_axi_mm_video_0_AWPROT;
output  [3:0] m_axi_mm_video_0_AWQOS;
output  [3:0] m_axi_mm_video_0_AWREGION;
output  [0:0] m_axi_mm_video_0_AWUSER;
output   m_axi_mm_video_0_WVALID;
input   m_axi_mm_video_0_WREADY;
output  [127:0] m_axi_mm_video_0_WDATA;
output  [15:0] m_axi_mm_video_0_WSTRB;
output   m_axi_mm_video_0_WLAST;
output  [0:0] m_axi_mm_video_0_WID;
output  [0:0] m_axi_mm_video_0_WUSER;
output   m_axi_mm_video_0_ARVALID;
input   m_axi_mm_video_0_ARREADY;
output  [63:0] m_axi_mm_video_0_ARADDR;
output  [0:0] m_axi_mm_video_0_ARID;
output  [31:0] m_axi_mm_video_0_ARLEN;
output  [2:0] m_axi_mm_video_0_ARSIZE;
output  [1:0] m_axi_mm_video_0_ARBURST;
output  [1:0] m_axi_mm_video_0_ARLOCK;
output  [3:0] m_axi_mm_video_0_ARCACHE;
output  [2:0] m_axi_mm_video_0_ARPROT;
output  [3:0] m_axi_mm_video_0_ARQOS;
output  [3:0] m_axi_mm_video_0_ARREGION;
output  [0:0] m_axi_mm_video_0_ARUSER;
input   m_axi_mm_video_0_RVALID;
output   m_axi_mm_video_0_RREADY;
input  [127:0] m_axi_mm_video_0_RDATA;
input   m_axi_mm_video_0_RLAST;
input  [0:0] m_axi_mm_video_0_RID;
input  [8:0] m_axi_mm_video_0_RFIFONUM;
input  [0:0] m_axi_mm_video_0_RUSER;
input  [1:0] m_axi_mm_video_0_RRESP;
input   m_axi_mm_video_0_BVALID;
output   m_axi_mm_video_0_BREADY;
input  [1:0] m_axi_mm_video_0_BRESP;
input  [0:0] m_axi_mm_video_0_BID;
input  [0:0] m_axi_mm_video_0_BUSER;
input  [63:0] pDstPxl_dout;
input   pDstPxl_empty_n;
output   pDstPxl_read;
input  [2:0] pDstPxl_num_data_valid;
input  [2:0] pDstPxl_fifo_cap;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg nSize_read;
reg nTimes_read;
reg pDstPxl_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [3:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    nSize_blk_n;
reg    nTimes_blk_n;
reg    pDstPxl_blk_n;
reg   [31:0] nTimes_1_reg_133;
reg    ap_block_state1;
reg   [27:0] nSizePC_reg_138;
reg   [59:0] p_cast_reg_145;
wire    ap_CS_fsm_state2;
wire   [59:0] grp_fu_86_p2;
reg   [59:0] bound_reg_160;
wire    ap_CS_fsm_state3;
wire    grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_start;
wire    grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_done;
wire    grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_idle;
wire    grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_ready;
wire    grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWVALID;
wire   [63:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWADDR;
wire   [0:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWID;
wire   [31:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWLEN;
wire   [2:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWSIZE;
wire   [1:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWBURST;
wire   [1:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWLOCK;
wire   [3:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWCACHE;
wire   [2:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWPROT;
wire   [3:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWQOS;
wire   [3:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWREGION;
wire   [0:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWUSER;
wire    grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WVALID;
wire   [127:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WDATA;
wire   [15:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WSTRB;
wire    grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WLAST;
wire   [0:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WID;
wire   [0:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WUSER;
wire    grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARVALID;
wire   [63:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARADDR;
wire   [0:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARID;
wire   [31:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARLEN;
wire   [2:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARSIZE;
wire   [1:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARBURST;
wire   [1:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARLOCK;
wire   [3:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARCACHE;
wire   [2:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARPROT;
wire   [3:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARQOS;
wire   [3:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARREGION;
wire   [0:0] grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARUSER;
wire    grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_RREADY;
wire    grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_BREADY;
wire    grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_strmDstPxl_read;
reg    grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_start_reg;
wire    ap_CS_fsm_state4;
wire   [31:0] grp_fu_86_p0;
wire   [27:0] grp_fu_86_p1;
reg   [3:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
reg    ap_ST_fsm_state4_blk;
wire   [59:0] grp_fu_86_p00;
wire   [59:0] grp_fu_86_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 4'd1;
#0 grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_start_reg = 1'b0;
end

aximm_test0_fill_data_times_v2_Pipeline_loop_preload_loop_burst grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_start),
    .ap_done(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_done),
    .ap_idle(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_idle),
    .ap_ready(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_ready),
    .m_axi_mm_video_0_AWVALID(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWVALID),
    .m_axi_mm_video_0_AWREADY(m_axi_mm_video_0_AWREADY),
    .m_axi_mm_video_0_AWADDR(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWADDR),
    .m_axi_mm_video_0_AWID(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWID),
    .m_axi_mm_video_0_AWLEN(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWLEN),
    .m_axi_mm_video_0_AWSIZE(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWSIZE),
    .m_axi_mm_video_0_AWBURST(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWBURST),
    .m_axi_mm_video_0_AWLOCK(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWLOCK),
    .m_axi_mm_video_0_AWCACHE(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWCACHE),
    .m_axi_mm_video_0_AWPROT(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWPROT),
    .m_axi_mm_video_0_AWQOS(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWQOS),
    .m_axi_mm_video_0_AWREGION(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWREGION),
    .m_axi_mm_video_0_AWUSER(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWUSER),
    .m_axi_mm_video_0_WVALID(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WVALID),
    .m_axi_mm_video_0_WREADY(m_axi_mm_video_0_WREADY),
    .m_axi_mm_video_0_WDATA(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WDATA),
    .m_axi_mm_video_0_WSTRB(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WSTRB),
    .m_axi_mm_video_0_WLAST(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WLAST),
    .m_axi_mm_video_0_WID(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WID),
    .m_axi_mm_video_0_WUSER(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WUSER),
    .m_axi_mm_video_0_ARVALID(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARVALID),
    .m_axi_mm_video_0_ARREADY(1'b0),
    .m_axi_mm_video_0_ARADDR(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARADDR),
    .m_axi_mm_video_0_ARID(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARID),
    .m_axi_mm_video_0_ARLEN(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARLEN),
    .m_axi_mm_video_0_ARSIZE(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARSIZE),
    .m_axi_mm_video_0_ARBURST(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARBURST),
    .m_axi_mm_video_0_ARLOCK(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARLOCK),
    .m_axi_mm_video_0_ARCACHE(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARCACHE),
    .m_axi_mm_video_0_ARPROT(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARPROT),
    .m_axi_mm_video_0_ARQOS(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARQOS),
    .m_axi_mm_video_0_ARREGION(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARREGION),
    .m_axi_mm_video_0_ARUSER(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_ARUSER),
    .m_axi_mm_video_0_RVALID(1'b0),
    .m_axi_mm_video_0_RREADY(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_RREADY),
    .m_axi_mm_video_0_RDATA(128'd0),
    .m_axi_mm_video_0_RLAST(1'b0),
    .m_axi_mm_video_0_RID(1'd0),
    .m_axi_mm_video_0_RFIFONUM(9'd0),
    .m_axi_mm_video_0_RUSER(1'd0),
    .m_axi_mm_video_0_RRESP(2'd0),
    .m_axi_mm_video_0_BVALID(m_axi_mm_video_0_BVALID),
    .m_axi_mm_video_0_BREADY(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_BREADY),
    .m_axi_mm_video_0_BRESP(m_axi_mm_video_0_BRESP),
    .m_axi_mm_video_0_BID(m_axi_mm_video_0_BID),
    .m_axi_mm_video_0_BUSER(m_axi_mm_video_0_BUSER),
    .strmDstPxl_dout(strmDstPxl_dout),
    .strmDstPxl_empty_n(strmDstPxl_empty_n),
    .strmDstPxl_read(grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_strmDstPxl_read),
    .strmDstPxl_num_data_valid(3'd0),
    .strmDstPxl_fifo_cap(3'd0),
    .bound(bound_reg_160),
    .nSizePC(nSizePC_reg_138),
    .wide_trip_count(nSizePC_reg_138),
    .p_cast_cast(p_cast_reg_145)
);

aximm_test0_mul_32ns_28ns_60_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 28 ),
    .dout_WIDTH( 60 ))
mul_32ns_28ns_60_2_1_U20(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_86_p0),
    .din1(grp_fu_86_p1),
    .ce(1'b1),
    .dout(grp_fu_86_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b1 == ap_CS_fsm_state4) & (grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_done == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_start_reg <= 1'b1;
        end else if ((grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_ready == 1'b1)) begin
            grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        bound_reg_160 <= grp_fu_86_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        nSizePC_reg_138 <= {{nSize_dout[31:4]}};
        nTimes_1_reg_133 <= nTimes_dout;
        p_cast_reg_145 <= {{pDstPxl_dout[63:4]}};
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

always @ (*) begin
    if ((grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_done == 1'b0)) begin
        ap_ST_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_done == 1'b1))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) & (grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_done == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        nSize_blk_n = nSize_empty_n;
    end else begin
        nSize_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        nSize_read = 1'b1;
    end else begin
        nSize_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        nTimes_blk_n = nTimes_empty_n;
    end else begin
        nTimes_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        nTimes_read = 1'b1;
    end else begin
        nTimes_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        pDstPxl_blk_n = pDstPxl_empty_n;
    end else begin
        pDstPxl_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
        pDstPxl_read = 1'b1;
    end else begin
        pDstPxl_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (1'b0 == ap_block_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b1 == ap_CS_fsm_state4) & (grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (nTimes_empty_n == 1'b0) | (nSize_empty_n == 1'b0) | (ap_done_reg == 1'b1) | (pDstPxl_empty_n == 1'b0));
end

assign grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_start = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_ap_start_reg;

assign grp_fu_86_p0 = grp_fu_86_p00;

assign grp_fu_86_p00 = nTimes_1_reg_133;

assign grp_fu_86_p1 = grp_fu_86_p10;

assign grp_fu_86_p10 = nSizePC_reg_138;

assign m_axi_mm_video_0_ARADDR = 64'd0;

assign m_axi_mm_video_0_ARBURST = 2'd0;

assign m_axi_mm_video_0_ARCACHE = 4'd0;

assign m_axi_mm_video_0_ARID = 1'd0;

assign m_axi_mm_video_0_ARLEN = 32'd0;

assign m_axi_mm_video_0_ARLOCK = 2'd0;

assign m_axi_mm_video_0_ARPROT = 3'd0;

assign m_axi_mm_video_0_ARQOS = 4'd0;

assign m_axi_mm_video_0_ARREGION = 4'd0;

assign m_axi_mm_video_0_ARSIZE = 3'd0;

assign m_axi_mm_video_0_ARUSER = 1'd0;

assign m_axi_mm_video_0_ARVALID = 1'b0;

assign m_axi_mm_video_0_AWADDR = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWADDR;

assign m_axi_mm_video_0_AWBURST = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWBURST;

assign m_axi_mm_video_0_AWCACHE = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWCACHE;

assign m_axi_mm_video_0_AWID = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWID;

assign m_axi_mm_video_0_AWLEN = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWLEN;

assign m_axi_mm_video_0_AWLOCK = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWLOCK;

assign m_axi_mm_video_0_AWPROT = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWPROT;

assign m_axi_mm_video_0_AWQOS = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWQOS;

assign m_axi_mm_video_0_AWREGION = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWREGION;

assign m_axi_mm_video_0_AWSIZE = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWSIZE;

assign m_axi_mm_video_0_AWUSER = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWUSER;

assign m_axi_mm_video_0_AWVALID = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_AWVALID;

assign m_axi_mm_video_0_BREADY = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_BREADY;

assign m_axi_mm_video_0_RREADY = 1'b0;

assign m_axi_mm_video_0_WDATA = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WDATA;

assign m_axi_mm_video_0_WID = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WID;

assign m_axi_mm_video_0_WLAST = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WLAST;

assign m_axi_mm_video_0_WSTRB = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WSTRB;

assign m_axi_mm_video_0_WUSER = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WUSER;

assign m_axi_mm_video_0_WVALID = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_m_axi_mm_video_0_WVALID;

assign strmDstPxl_read = grp_fill_data_times_v2_Pipeline_loop_preload_loop_burst_fu_74_strmDstPxl_read;

endmodule //aximm_test0_fill_data_times_v2
